chore: fix hitachi healthcheck when running mtls acceptance tests (#310)
* chore: fix hitachi heathcheck on test:acceptance:proxy:mtls run

* chore: bump version

* chore: bump version

* chore: bump version

* chore: bump version

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -87,8 +87,9 @@ jobs:
           test-script: npm test
 
       - name: Acceptance & environment emulation tests
-        # the script is basically `npm run test:acceptance:docker && npm run test:acceptance:proxy`
-        # but with some extra logging and error handling to help debug failures
+        # the script is basically `npm run test:acceptance:docker && npm run test:acceptance:proxy
+        # && npm run test:acceptance:proxy:mtls` but with some extra logging and error handling to
+        # help debug failures
         run: |
           set +e
           docker compose -f compose.yml -f test/acceptance/compose.yml \
@@ -107,9 +108,17 @@ jobs:
             docker compose down --remove-orphans
             exit 1
           fi
+          npm run test:acceptance:proxy:mtls
+          if [ $? -ne 0 ]; then
+            echo -e '\n\n====> Dumping DAL logs...\n'
+            docker logs fcp-dal-api-fcp-dal-api-1 | jq
+            echo -e '\n\n====> Dumping upstream logs...\n'
+            docker logs fcp-dal-api-upstream-mock-1
+
+            docker compose down --remove-orphans
+            exit 1
+          fi
           docker compose down --remove-orphans
-        # TODO: re-enable mTLS tests when startup health check issue is resolved
-        #  && npm run test:acceptance:proxy:mtls
 
       - name: Sonar Cloud Scan
         if: github.actor != 'dependabot[bot]'
