add more detailed coverage

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -28,12 +28,18 @@ jobs:
           npm audit --omit=dev
           npm ci
           npm run lint
-          npm test -- --coverage | tee ./coverage.txt || tests_failed=1
+          npm test -- --coverage --coverageReporters="text" --coverageReporters="lcov" > coverage/coverage.txt 2>&1 || echo "TESTS_FAILED=true" >> $GITHUB_ENV
 
       - name: Test and Coverage
         uses: MishaKav/jest-coverage-comment@main
         with:
-          coverage-path: ./coverage.txt
+          coverage-path: coverage/coverage.txt
+
+      - name: Fail job if tests failed
+        if: env.TESTS_FAILED == 'true'
+        run: |
+          echo "Tests or coverage threshold failed"
+          exit 1
 
       - name: Test Docker Image Build
         run: |
